/rc_serial_driver:
  ros__parameters:
    device_name: /dev/ttyACM0
    # device_name: /dev/ttyUSB0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"


/v4l2_camera_node:
  ros__parameters:
    camera_info_url: package://rc_vision_bringup/config/camera_info.yaml
    auto_exposure: 1
    exposure_time_absolute: 112
    image_size:
      - 1280
      - 720


/cam_detector_container:
  ros__parameters:
    # cam_rgb_topic: /image_raw
    cam_rgb_topic: /camera/color/image_raw
    debug: True
