/realsense_detector_container:
  ros__parameters:
    # 注意有两个相机，对应不同的话题
    # cam_rgb_topic: /image_raw
    cam_rgb_topic: /camera/color/image_raw
    publish_topic: /realsense/results
    publish_rgb_topic: /realsense/rgb_results
    debug: True

    # 对应红方和蓝方的，红方在左侧场地，蓝方在右侧场地
    # 0: red, 1: blue
    # game_mode: False
    game_mode: True


    
    
